name: Check Formatting

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Formatters
      run: |
        pip install black isort
    - name: Check formatting with Black
      run: black --check .
    - name: Check import sorting with isort
      run: isort --check-only .