name: Security Scan

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Bandit
      run: pip install bandit
    - name: Run Bandit
      run: bandit -r . -ll # -r . scansiona ricorsivamente, -ll reporta problemi di livello MEDIO e ALTO